export enum Menu {
    adminDashboard = 'admin-dashboard',
    clientDashboard = 'client-dashboard',
    adminMerchant = 'admin-merchant',
    adminMerchantCategory = 'admin-merchant-category',
    adminMerchantProduct = 'admin-merchant-product',
    adminOrder = 'admin-order',
    adminInvoice = 'admin-invoice',
    adminShifting = 'admin-shifting',
    adminUser = 'admin-user',
    adminRole = 'admin-role',
    adminAccess = 'admin-access',
    adminConfiguration = 'admin-configuration',
    adminDataMeta = 'admin-data-meta',
    adminReport = 'admin-report',
    adminChart = 'admin-chart',
    adminSetting = 'admin-setting',
    adminAi = 'admin-ai',
}